### ISSUE TITLE
Problem: default hd-path flag is not "44'/394'/0'/0/1"

### ISSUE THREAD

**Issue by allthatjazzleo** [crypto-org-chain/chain-main#166]
https://github.com/crypto-com/chain-main/blob/4be43e645c09093943970b6abc19eb4dd7de5933/app/prefix.go#L13

By default, it uses (0, 0) bip44 HD path not  "44'/394'/0'/0/1"
Should make default hd-path flag to "44'/394'/0'/0/1"?

**Comment by calvinaco** [comment]
> const (
> CoinType = 394
> FundraiserPath = "44'/394'/0'/0/1"
> )
> 
> it's already done
> by #155, #167

#155, #167 is referring to a different issue. In this issue the default hd-path flag seems not affected by the fundraiser path config so the issue should still exist.

**Comment by calvinaco** [comment]
For future reference, the default HD path is able to use the `CoinType` in config, but the account and index is (0,0)

In Testnet, the default path is `m/44'/1'/0'/0/0`

**Comment by tomtau** [comment]
seems this is no longer relevant -- feel free to reopen the issue though
