### ISSUE TITLE
Problem: integration test speed is slow

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/chain-main#197]
currently, same test is done twice.

nix-integration-test: check-network
	nix-shell integration_tests/shell.nix --run "pytest -v -n 3 -m 'not ledger' --dist loadscope"
	nix-shell integration_tests/shell.nix --run "pytest -v -m ledger"

i suggest separate ledger and non-lendger to different folders,
so ,it makes total integration test faster

**Comment by yihuang** [comment]
it's separated by marks, "not ledger" and "ledger", they are not overlapped.

**Comment by yihuang** [comment]
currently ledger tests are running sequentially with other tests, the reason for that is ledger simulator is too costly, slows down the whole github action vm.

**Comment by yihuang** [comment]
I increased xdist's worker number to 7, the time dropped a bit.
pytest-xdist's scheduling strategy could have some optimization, currently it treat fast and slow test cases as the same, if we can distribute slow test cases more evenly on workers, we could further shorten the test running time.

**Comment by tomtau** [comment]
it looks like the speed has been a bit improved, but has to be balanced, so that it doesn't timeout on CI -- feel free to reopen this if there's some obvious way for more improvements
