### ISSUE TITLE
Problem: no testnet compatibility tests

### ISSUE THREAD

**Issue by tomtau** [crypto-org-chain/chain-main#204]
as there's already a public testnet running (on top of unreleased SDK version), it'll be good to find out early if something broke with a simple dependency upgrade (and one needs to trigger some network upgrade proposal and/or provide some conversion tools), so this includes:
1. parsing genesis.json
2. processing block data / transactions -- (either from network or reading data persisted by the old binary)
3. external API changes

**Comment by yihuang** [comment]
I guess we can make an integration test case to join the running testnet with recent binary. and issue a warning if it don't work.

**Comment by yihuang** [comment]
https://github.com/cosmos/cosmos-sdk/pull/7526/files#diff-046f100a1eb97e25aa6ecc5b5a618c222775184faf805d7a7cbb9e9e6a92aba1R47

master binary can't decode the testnet genesis file because of above change.

**Comment by yihuang** [comment]
- investigate if it's possible to do snapshot in tendermint before upgrade, then we don't need to worry about migrating old abci messages.
- then we can focus on migration of abci state storage.

**Comment by tomtau** [comment]
this was more relevant to pre-release versions which broke in undocumented ways -- it should be clearer now, but perhaps we can open separate issues for mainnet/testnet once the final things are up and running
