### ISSUE TITLE
Problem: missing environment information for pystarport

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/chain-main#217]
when nix-shell, pystarport serve.
each node port is unclear,

so for development and and easy managing multiple nodes,
produce setup.sh file which has all environment variables.

so user or developer can activate setup.sh, and
test outside nix,
using nodejs, and other languages to interact with the chain-maind

including)
- port for each services
- addresses for each account

**Comment by tomtau** [comment]
afaik this is documented in the supervisor ini file -- @yihuang ?
feel free to reopen if this is still an issue
