### ISSUE TITLE
Problem: cosmovisor is not complete

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/chain-main#226]
- how new user downloads the old versions of binary.
- how minor versions are upgraded.
- contingency plan in case of total failure of upgrade.

and it seems cosmovisor logic is simple enough to write our own version.

**Comment by yihuang** [comment]
# Cosmovisor refinement proposal

## Semantic versioning

Adopt the semantic versioning conventions, minor and patch versions are backward compatible, major versions are breaking, which needs coordination on chain to do the upgrade. The major version `v0` is the genesis version.

The plan name of software upgrade proposal on chain just refer to the major version number, like `v1`, `v2`, `v3`, etc. Include the hash of package in the `info` field.

## Binary package

A binary package contains all the major versions since genesis, with the most recent minor and patch versions in each major version, so it contains all the binaries needed to sync the whole chain. For example:

```
.
└── v0
    └── version  # contains the full version number, maybe other metadata for this version
    └── bin
        └── chain-maind
└── v1
    └── version
    └── bin
        └── chain-maind
```

Users are always safe to upgrade to the most recent binary package, no matter it's minor or major version upgrade, as long as the maintainer follows the semantic versioning rules. We can even setup something to auto-upgrade chain binary for the users who trust the official devs blindly.

The upgrade of a binary package should be atomic.

The upgrade of binary package can be used for both minor version upgrades and preparing for the next on chain major version upgrade.

## Cosmovisor

Cosmovisor maintains a symbolic link to the current major version used on chain (of the local view) in the binary's `home` directory, and switch it according to the upgrade events on chain.

```
.
└── current -> $PACKAGE_HOME/v1
```

Cosmovisor starts the chain binary in the `current` directory in a subprocess, captures the stdout and stderr, when upgrade events happens, the chain binary will log a special message to stdout, cosmovisor will recognize it and change the `current` link accordingly, then restart the chain process with the new binary.

### Environment variables

- `DAEMON_NAME` 

  the name of chain binary, e.g. `chain-maind`.

- `PACKAGE_HOME` 

  the path to the current package, when package upgraded, either restart cosmovisor with the new path or instruct it to change the path at runtime.

## Cache the unchanged old major versions

A naive way to implement the package is just use a tarball, although user will re-download the unchanged old major versions, but it maybe fine if on chain major version upgrade is not frequent.

There are different ways to optimize this:

- nix
- layered docker image
- rsync with immutable directory layout
- git-lfs

**Comment by yihuang** [comment]
several user work flows:
- User wants to sync chain from genesis to latest
  - download the genesis binary, enable auto-download in cosmovisor, will have the first minor version of each major versions.
  - download the package at once which contains the most recent minor versions of each major versions.
- User wants to keep syncing the chain in the future
  - enable auto-download in cosmovisor, will auto-download the first minor version of each major versions.
  - subscribe to package upgrade channel, auto-upgrade in some way, will have the most recent minor versions.

**Comment by tomtau** [comment]
> what happens when third-party released a version and get passed?

in general, the assumption is that for validator operation, one should be more careful and to the upgrades manually -- if it gets passed by major players and it was discussed upfront, it's likely ok.

Maybe more general flow that should be tested is -- what if the upgrade is wrong/to be reverted (e.g. it's later discovered some module's functionality doesn't work correctly). For that, the upgrade module defines another proposal type for governance: "CancelSoftwareUpgradeProposal"

**Comment by tomtau** [comment]
post-mainnet releases should follow semver: https://github.com/crypto-org-chain/chain-main/pull/391/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R124
+ Go Releaser now produces cosmovisor-compatible binaries, so this could be revisited later
