### ISSUE TITLE
Problem: cannot add python package with poetry in pystarport

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/chain-main#229]
1. install protobuf to pystarport
cd pystartport
poetry add protobuf

2. begin nix-shell
nix-shell ./integration_tests/shell.nix 
error: list index 0 is out of bounds, at /nix/store/26zdy39r2hx0vpj1mj4lvmsgs3q71kpd-nixpkgs-21.03pre243895.72b9660dc18/nixpkgs/pkgs/development/tools/poetry2nix/poetry2nix/mk-poetry-dep.nix:69:27
(use '--show-trace' to show detailed location information)

target os:
ubuntu 20
mac osx

integration_tests is working fine, only pystarport

**Comment by tomtau** [comment]
not sure if still relevant -- feel free to reopen if it is
