### ISSUE TITLE
Problem: missing comments about pytest reserved variables

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/chain-main#230]
```
@pytest.fixture(scope="session")
def cluster(worker_id, pytestconfig, tmp_path_factory):
```

worker_id, pytestconfig, tmp_path_factory is pytest pre-defined variables.
for easy understanding, add some comments about these pre-definitions

**Comment by yihuang** [comment]
these are pytest fixtures, some builtin, some provided by plugins.
worker_id is provided by xdist plugin, others are builtin.

**Comment by yihuang** [comment]
- [pytest.fixture](https://docs.pytest.org/en/stable/fixture.html)
- [tmp_path_factory](https://docs.pytest.org/en/stable/reference.html#std-fixture-tmp_path_factory)
- [pytest-xdist](https://pypi.org/project/pytest-xdist/)

**Comment by tomtau** [comment]
seems not relevant any more -- feel free to reopen if it is
