### ISSUE TITLE
Problem: no brand name in binary name

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/chain-main#232]
Current binary has a common name `chain-maind`, should we add crypto-com into it?

**Comment by tomtau** [comment]
will check what's preferred. the binary name may become too long, perhaps something like `cdc-chaind` may be a good compromise

**Comment by leejw51crypto** [comment]
how about gcro?
g <- golang
cro <- CRO

**Comment by yihuang** [comment]
> will check what's preferred. the binary name may become too long, perhaps something like `cdc-chaind` may be a good compromise

what's the cdc stands for?

**Comment by tomtau** [comment]
> > will check what's preferred. the binary name may become too long, perhaps something like `cdc-chaind` may be a good compromise
> 
> what does the cdc mean?

crypto-dot-com

**Comment by devashishdxt** [comment]
`cdc-chaind` sounds good.

**Comment by tomtau** [comment]
now, it'd be `cdo-chaind` :D but given a lot of integrations / scripts from testnets and crossfire assume "chain-main", let's keep it that way for now... if it's  a problem, we can later open a discussion or ADR: https://github.com/crypto-org-chain/chain-main/pull/391/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R26
