### ISSUE TITLE
Problem: missing physical multiple nodes setup in pystarport

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/chain-main#254]
adding physical multiple nodes setup using pystarport in local lan environment.
so can setup  tens of nodes easily.

1. install pystartport for each manchine
2. run pystarport with deamon mode
3. one node becomes the supervisor, installing and setup files

can talk with json or protobuf, using tcp/ip
also utilize upnp to gather nodes in one place.

or can use rabbitmq or zeromq for communication

**Comment by yihuang** [comment]
I think you can try
- [nixops](https://nixos.org/nixops/manual)
- or [ansible](https://www.ansible.com)

**Comment by tomtau** [comment]
starport has this "starport network" feature now: https://www.youtube.com/watch?v=DhciTJHxvAY
