### ISSUE TITLE
Problem: no autoformatting in Makefile

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/chain-main#256]
add auto-formatter to Makefile
for example)
make fmt
which autoformats all source code in the repo

1. go lang files
- use golang formatter using nix
2. python 
- use black, flake8, isort formatter
3. nix files
- use nixpkgs-formatter

**Comment by yihuang** [comment]
I think you can config IDE for individual file types?

**Comment by tomtau** [comment]
vscode will do gofmt on save
