### ISSUE TITLE
Problem: statesync fails sometimes

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/chain-main#257]
FAILED integration_tests/test_basic.py::test_statesync - AssertionError: syncing

sometimes, it fails  in test_statesync

check whether there is timing related issues

**Comment by yihuang** [comment]
I've see failures too, possibly fixed by this change: https://github.com/crypto-com/chain-main/pull/260/files#diff-dd3fb740cd9aec2d8510529d775f69299bee17dc7e7d83c60ae1d4f8c1318c65R70.

**Comment by tomtau** [comment]
Does this still happen? this may be related to that persistent peers issue -- so no longer relevant, but feel free to reopen
