### ISSUE TITLE
Problem: missing environment variable for chain-id, keyring-backend, home

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/chain-main#266]
add three env-variables.

for example)
-- CRYPTO_CHAIN_ID : --chain-id
-- CRYPTO_KEYRING_BACKEND: --keyring-backend
-- CRYPTO_HOME: --home

also printout these value in the beginning

**Comment by tomtau** [comment]
I think these may already be there: https://github.com/cosmos/cosmos-sdk/blob/master/server/doc.go#L14
just under different names auto-generated by Viper from command line arguments + binary name
