### ISSUE TITLE
Problem: missing markdown document of hw ledger

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/chain-main#268]
add document for below

1. adding a ledger address
2. removing a ledger address
3. show a ledger address
4. list hw addresses

**Comment by tomtau** [comment]
ref https://github.com/crypto-com/ledger-crypto/issues/6#issuecomment-723647988

**Comment by tomtau** [comment]
documented in chain-docs / https://crypto.org/docs/wallets/ledger.html
