### ISSUE TITLE
Problem:lack of info in ledger option

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/chain-main#273]
add these information, so that 
user can use ledger easily

1. --sign-mode amino-json in `tx bank send`
in using --ledger option

for example)
 chain-maind tx bank send $HW1 $SIGNER2  321basecro --keyring-backend test --chain-id test --ledger  --sign-mode amino-json

2.  key generation option for ledger in `keys add` 
chain-maind keys add hw  --ledger --keyring-backend test

**Comment by tomtau** [comment]
documented in https://crypto.org/docs/wallets/ledger.html
