### ISSUE TITLE
Problem: no aggregated TX history command

### ISSUE THREAD

**Issue by tomtau** [crypto-org-chain/chain-main#285]
Currently, it seems one may need to issue multiple commands to retrieve tx history (`chain-maind query txs --events message.sender=<ADDRESS>`, `chain-maind query txs --events  transfer.recipient=<ADDRESS>`, ...).
It may be handy to have a shorthand command / API for that (if it doesn't exist)

**Comment by yihuang** [comment]
- `message.sender=<ADDRESS>` is all transactions issued by user
- for transactions user can receive, I think only transfer and ibc-transfer?

**Comment by tomtau** [comment]
summary from Slack:
* message.sender
* transfer.recipient
* withdraw_rewards.validator
* ibc_transfer.receiver
