### ISSUE TITLE
Problem: ibc live through export-upgrade is not tested

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/chain-main#288]
By increasing the chain version number in chain-id, ibc state in previous chain should be able to keep working after upgrade.

**Comment by tomtau** [comment]
one other good thing to test will be to configure IBC connection at genesis (AFAIK should be possible) instead of dynamically created at runtime

**Comment by yihuang** [comment]
> one other good thing to test will be to configure IBC connection at genesis (AFAIK should be possible) instead of dynamically creating it later

When you do export after setup ibc connection, the ibc state should be dumped into the genesis file already. I haven’t tried to config it manually though.

**Comment by leejw51crypto** [comment]
increasing chain-id would be like these ?
testnet-croeseid-2
testnet-croeseid-3
...
