### ISSUE TITLE
Problem: export upgrade is not tested

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/chain-main#289]
simulate doing export upgrade manually (without upgrade module).

- run devnet with a release version binary for a while and stop
- do export (and migrate genesis if necessary) and set genesis_time to near future
- override genesis file and do `unsafe_reset_all`
- startup, wait for block generation

**Comment by JayT106** [comment]
@yihuang Is the test done the correct testing?
https://github.com/JayT106/chain-main/commit/f5d2496d57917d826d96bf95de031765cccbfc46
What's the purpose to export the chain state and override the genesis?

**Comment by yihuang** [comment]
I think the intension of this test is like: are there breaking changes in genesis file from last production running version to current version.
