### ISSUE TITLE
problem: RPC error -32603 - Internal error: timed out waiting for tx to be included in a block

### ISSUE THREAD

**Issue by HankFit247** [crypto-org-chain/chain-main#328]
RPC error -32603 - Internal error: timed out waiting for tx to be included in a block

Brand NEW AWS 1-Click Instance Install, all was working fine, then all of a sudden I started to see this error again this morning.

I double check, and I am indeed running 0.8.0-rc1

**Comment by nicobilliotte** [comment]
Same with a fast sync node 0.8.0-rc1
PB visible everythime time I do unjail transaction, or if the server is a bit busy.

`{"body":{"messages":[{"@type":"/cosmos.slashing.v1beta1.MsgUnjail","validator_addr":"#Validator_addr#"}],"memo":"",**"timeout_height":"0"**,"extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[{"denom":"basetcro","amount":"20000"}],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]}

confirm transaction before signing and broadcasting [y/N]: y
Error: RPC error -32603 - Internal error: timed out waiting for tx to be included in a block`

Anyway the transaction is made, but with timeout_height = 0 it shouldnt happen it's maybe a cosmos SDK problem ?

**Comment by tomtau** [comment]
This looks like an issue related to the default tx broadcast mode (I assume it can be resolved if one instead used "async" mode and checked the tx status later) -- feel free to reopen this issue if this can be reproduced on 0.9.1 after the testnet upgrade
