### ISSUE TITLE
Problem: account sequence mismatch, expected 5, got 4: incorrect account sequence

### ISSUE THREAD

**Issue by Vanlee-S** [crypto-org-chain/chain-main#330]
When trying to execute commands from #Transactions section

tx distribution withdraw-rewards
tx staking delegate

transactions did not go through and issue

{**"height": "0"**, "txhash": "9CC60D273270852AE6F783641F9EC549FBEA7800F7BDBB07FBCF4B3464421C19", "codespace": "sdk", "code": 32
, "data": "", "raw_log": "**account sequence mismatch, expected 5, got 4: incorrect account sequence**", "logs": [], "info": "", "
gas_wanted ":" 800000 "," gas_used ":" 42136 "," tx ": null," timestamp ":" "}

**Solved the problem by restarting sync**
Stop the chain-maind
and
chain-maind start

**Comment by tomtau** [comment]
This looks like an issue if one had an old state and tried to broadcast the transaction constructed against the old state... so should be resolvable by restarting / getting the latest state... feel free to reopen this issue if this can be reproduced on 0.9.1 after the testnet upgrade

**Comment by mircea-c** [comment]
Would like to reopen this issue if possible. Reproduced the issue consistently with `v2.0.1`.

Only fixed with a restart of the chain service.

```
{"body":{"messages":[{"@type":"/cosmos.bank.v1beta1.MsgSend","from_address":"cro1pcaz55jkjvczlup8lxrnn6pv8jv2qqkfrevstt","to_address":"cro1pf97sgze8790msdq4pqx9syhf5x6twrx7w2vgq","amount":[{"denom":"basecro","amount":"300000000"}]}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[{"denom":"basecro","amount":"10000"}],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]}

confirm transaction before signing and broadcasting [y/N]: y
{"height":"0","txhash":"6C758CDCCE006E110FAC350AAAB12340B8BDE5AFE8AD8832C4E2403F56080BA1","codespace":"sdk","code":32,"data":"","raw_log":"account sequence mismatch, expected 519, got 371: incorrect account sequence","logs":[],"info":"","gas_wanted":"200000","gas_used":"41691","tx":null,"timestamp":""}
```

**Comment by Johngbrownlll** [comment]
Sent from ProtonMail mobile

-------- Original Message --------

**Comment by tomtau** [comment]
@mircea-c are the steps the same?
1. tx distribution withdraw-rewards
2. tx staking delegate

**Comment by mircea-c** [comment]
@tomtau no. This was a `tx bank send` transaction

**Comment by tomtau** [comment]
1. tx distribution withdraw-rewards
2. tx bank send
?

**Comment by mircea-c** [comment]
There is only one step. `tx bank send`. As soon as it happens once, all transactions will fail with the same issue afterwards.
The only way this is fixed is by restarting the service.

**Comment by tomtau** [comment]
@mircea-c does the first TX succeed ? if it succeeded, then it's likely the node isn't sync up -- so may wait longer or use a different node with `--node` arg. If it didn't succeed, then it's the mempool state, so can look into the `[mempool]` section in config.toml

**Comment by mircea-c** [comment]
I'm not sure what you mean by first transaction. As I explained, there are no previous transactions, just the `tx bank send`. There are no staked tokens so no rewards to withdraw. 

The node is synced up to the network. Status endpoint shows `catching_up` false and the block height is the same as shown on explorer. This is also proven by the fact that the service restart only catches up 1-2 blocks before it's synced again.

I understand this is not a lot of information, and pretty hard to reproduce, but it is not related to the node sync.

**Comment by tomtau** [comment]
> there are no previous transactions

why would the account sequence be 5 or 4 if there were now previous transactions?
Anyway, this looks like a different issue than the originally posted one

**Comment by mircea-c** [comment]
The previous transactions were also `tx bank send`. This address does not have any tokens stake so no rewards are being claimed. This looks exactly like the original issue as there is no reason for this wallet sequence numbers to be out of sync.

**Comment by ironsf** [comment]
how to reset seunce?
