### ISSUE TITLE
Problem: invalid Bech32 prefix; expected tcrocnclconspub, got tcropub

### ISSUE THREAD

**Issue by dck0087** [crypto-org-chain/chain-main#331]
Following this guide and up to step 4-3:
https://chain.crypto.com/docs/getting-started/testnet-azure-1click.html#step-4-join-as-a-validator

Have created the config as per the example however when running the command am receiving this error:
Enter keyring passphrase:
Error: invalid Bech32 prefix; expected tcrocnclconspub, got tcropub
Usage:
  chain-maind tx staking create-validator [flags]

Is this possibly the version is out of date to accept the latest public keys?

**Comment by allthatjazzleo** [comment]
maybe related to this [issue](https://github.com/crypto-com/chain-docs/issues/76)

**Comment by lezzokafka** [comment]
Hello @dck0087 ,would you mind to share the `create-validator` transaction with us for troubleshooting?

**Comment by tomtau** [comment]
It's hard to tell what went wrong here...
feel free to reopen this issue if this can be reproduced on 0.9.1 after the testnet upgrade though
