### ISSUE TITLE
Problem: chain don't make progress when running slow in github action environment

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/chain-main#339]
https://github.com/crypto-com/chain-main/pull/326#issuecomment-753796226

it seems in github action execution environment, when resources running low, like when using too many testing workers, some tasks don't finish even with very long timeouts, currently it's solved by lowering the number of testing workers, but it might worth to further investigate.

**Comment by tomtau** [comment]
main issue is https://github.com/crypto-org-chain/chain-main/issues/385
