### ISSUE TITLE
Problem:  dead nodes stuck in peers list

### ISSUE THREAD

**Issue by HankFit247** [crypto-org-chain/chain-main#344]
AWS 1-Click, FRESH v8 build versus an upgrade from v7.

./chain-maind start
Shows lots of peers that I am unable to connect to.  I assume IP address changes, and then these peers are not getting updated and/or pruned out.

How often does the Peers list get updated, and old Peers get removed?

looks like ./chain-maind unsafe-reset-all which does the following:

INF Removed existing address book file=/root/.chain-maind/config/addrbook.json
INF Removed all blockchain history dir=/root/.chain-maind/data
INF Reset private validator file to genesis state keyFile=/root/.chain-maind/config/priv_validator_key.json stateFile=/root/.chain-maind/data/priv_validator_state.json
root@blockchain-vm:~# 

root@blockchain-vm:~# ./chain-maind validate-genesis
File at /root/.chain-maind/config/genesis.json is a valid genesis file

might help.  but I don't want to reset .chain-maind/data

The seeds return addresses that are offline for days. I think cleaning the addrbook will not help.  But rather the seeds need to prune themselves?

**Comment by tomtau** [comment]
I think this was a wrong config on the seed nodes side -- it should have been resolved...
feel free to reopen this issue if this can be reproduced on 0.9.1 after the testnet upgrade though
