### ISSUE TITLE
Problem: chain-maind leaks dbus-daemon processes

### ISSUE THREAD

**Issue by argusb** [crypto-org-chain/chain-main#348]
**Describe the bug**
The chain-maind binary release for v8 RC1 ( https://github.com/crypto-com/chain-main/releases/download/v0.8.0-rc1/chain-main_0.8.0-rc1_Linux_x86_64.tar.gz ) leaks a dbus-daemon process on every run.

**To Reproduce**
Just run the binary a number of times, you don't even have to execute anything "real", just display the usage info.
Example CLI to test:
```# Get the current number of dbus-daemons:
pgrep -f -l dbus-daemon | wc -l
# Run chain-maind 10 times:
for i in $(seq 1 10); do
  ./chain-maind -h >/dev/null
done
# Get the new count of dbus-daemon processes:
pgrep -f -l dbus-daemon | wc -l
```

Result:
```
 v8]$ pgrep -f -l dbus-daemon | wc -l ; for i in $(seq 1 10) ; do ./chain-maind -h >/dev/null ; done ; pgrep -f -l dbus-daemon | wc -l
1
11
 v8]$ pgrep -f -l dbus-daemon | wc -l ; for i in $(seq 1 10) ; do ./chain-maind -h >/dev/null ; done ; pgrep -f -l dbus-daemon | wc -l
11
21
```

**Expected behavior**
No dbus-daemon processes should be leaking, this leads to resource exhaustion ( number of processes, number of open files).

**Desktop (please complete the following information):**
 - OS: Tested on CentOS 7.9, Oracle Linux 7.9 and (just for giggles) CentOS 6.10
 - Version: 8 rc1

**Additional context**
This _might_ be a (RH)EL specific issue.

**Comment by esspam** [comment]
Fyi: on Ubuntu 20.04.1 LTS, chain-maind v0.8.0-rc1:
```
pgrep -f -l dbus-daemon | wc -l ; for i in $(seq 1 10) ; do chain-maind -h >/dev/null ; done ; pgrep -f -l dbus-daemon | wc -l
2
2
pgrep -f -l dbus-daemon | wc -l ; for i in $(seq 1 10) ; do chain-maind -h >/dev/null ; done ; pgrep -f -l dbus-daemon | wc -l
2
2
```
there seems to be no problem.

**Comment by tomtau** [comment]
maybe good to get the version of the dbus-deamon in different distributions?

**Comment by argusb** [comment]
> maybe good to get version information of each dbus-deamon across different distributions?

EL6: dbus-1.2.24-11.el6_10.x86_64
EL7: dbus-1.10.24-15.0.1.el7.x86_64

**Comment by argusb** [comment]
Also tested on CentOS8: no processes are leaking.
OS-version: 8.3.2011
dbus version: dbus-1.12.8-11.el8.x86_64

**Comment by tomtau** [comment]
This looks like an issue specific to those distributions / dbus versions -- perhaps the best will be to reach out to maintainers of those distribution versions whether the dbus package could be upgraded?
If not, we can perhaps add a section in documentation to help people troubleshoot this issue (and upgrade their dbus package manually) -- feel free to open a PR on chain-docs for it
