### ISSUE TITLE
Problem:  node-listener.service does not exist

### ISSUE THREAD

**Issue by HankFit247** [crypto-org-chain/chain-main#374]
sudo systemctl enable node-listener.service
Failed to enable unit: Unit file node-listener.service does not exist.

**Comment by HankFit247** [comment]
/etc/systemd/system
sudo nano node-listener.service
sudo systemctl enable node-listener.service

Copy contents below into the file.

[Unit]
Description=Chain-maind
ConditionPathExists=/chain/chain-maind
After=network.target

[Service]
Type=simple
User=crypto
Group=crypto
LimitNOFILE=4096

WorkingDirectory=/chain

ExecStart=/chain/chain-maind start --home /chain/.chain-maind --log_level warn

SyslogIdentifier=chain-maind

Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target

**Comment by tomtau** [comment]
@HankFit247 is this related to one of the AWS / Azure marketplace deployment images?

**Comment by tomtau** [comment]
feel free to reopen this issue if this can be reproduced on the latest AWS or Azure marketplace deployment images
