### ISSUE TITLE
Problem: goreleaser config not releasing for Arm64

### ISSUE THREAD

**Issue by tomtau** [crypto-org-chain/chain-main#376]
Darwin arm64 for M1
Linux arm64 for AWS Graviton etc.

**Comment by leejw51crypto** [comment]
started

**Comment by tomtau** [comment]
For reference, Tendermint goreleaser config: https://github.com/tendermint/tendermint/blob/master/.goreleaser.yml

**Comment by leejw51crypto** [comment]
ok, i'm working on it now
