### ISSUE TITLE
Problem: unstable join validator integration test

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/chain-main#385]
https://github.com/crypto-org-chain/chain-main/pull/381/checks?check_run_id=1968276739#step:5:349

**Comment by yihuang** [comment]
https://github.com/crypto-org-chain/chain-main/pull/387/checks?check_run_id=1969411637#step:5:440

**Comment by tomtau** [comment]
> https://github.com/crypto-org-chain/chain-main/pull/387/checks?check_run_id=1969411637#step:5:440

that one seems to be https://github.com/crypto-org-chain/chain-main/issues/388 -- is this a duplicate issue?

**Comment by yihuang** [comment]
> > https://github.com/crypto-org-chain/chain-main/pull/387/checks?check_run_id=1969411637#step:5:440
> 
> that one seems to be #388 -- is this a duplicate issue?

yes

**Comment by tomtau** [comment]
Here IBC test failed: https://github.com/crypto-org-chain/chain-main/pull/390/checks?check_run_id=1976907366#step:5:8133
again the same?

**Comment by yihuang** [comment]
> Here IBC test failed: https://github.com/crypto-org-chain/chain-main/pull/390/checks?check_run_id=1976907366#step:5:8133
> again the same?

I think so, something running very slow I guess.

**Comment by huangxufu** [comment]
I guess we can close this one now, seems pretty stable recently.

**Comment by yihuang** [comment]
I think this one can be closed now, pretty stable recently.
