### ISSUE TITLE
Problem: protobuf files are using v1beta from cosmos-sdk

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/chain-main#395]
Version the protobuf files in proto directory properly.

Options([source](https://github.com/crypto-org-chain/chain-main/pull/381#discussion_r584483594)):
1. follow Cosmos SDK's current version: keep "v1beta1"?
2. follow chain-main's "global version" module -- mainnet base repo will be v1, so subscriptions will likely be "v2"?
3. each module versions independently -- so subscriptions can be "v1" regardless of what mainnet base repo is and will only be bumped to "v2" if there are breaking changes in subscriptions?

**Comment by tomtau** [comment]
the third option probably makes most sense -- e.g. even if there's a "breaking" v2 of chain-main, API of some modules may remain the same / v1, so for external parties integrating it, it'll be more convenient
