### ISSUE TITLE
Problem: genesis file is updated non-atomically

### ISSUE THREAD

**Issue by tomtau** [crypto-org-chain/chain-main#398]
If the machine experiences a sudden fault, such as a power outage, while running the `init` command, the genesis file will be corrupted.
The atomic update be accomplished by writing the file to a temporary output (such as `genesis.json.tmp`), syncing that output using `file.Sync()`, calling `os.Rename` to rename the `genesis.json.tmp` to `genesis.json`, and finally applying a final `Sync()`.
https://github.com/crypto-org-chain/chain-main/blob/master/cmd/chain-maind/app/app.go#L136

**Comment by yihuang** [comment]
Another approach is to patch it in `NewDefaultGenesisState`(`app/genesis.go`), then no need to override the command.
