### ISSUE TITLE
Documentation repository is missing

### ISSUE THREAD

**Issue by orfeas0** [crypto-org-chain/chain-main#400]
**Describe the bug**
The chain's readme redirects to a non-existent documentation repo.

**To Reproduce**
1. Go to https://github.com/crypto-org-chain/chain-main
2. Click on '_Github Repository_' under **4. Documentation**

**Result**
Get redirected to https://github.com/crypto-org-chain/chain-docs which is yet to be created.

**Solution**
Either change readme.md to link to https://github.com/crypto-com/chain-docs or create the new repo.

**Comment by tomtau** [comment]
thanks! The repository has been moved under the new GH org: https://github.com/crypto-org-chain/chain-docs
