### ISSUE TITLE
Problem: dev setup for macOS not fully documented

### ISSUE THREAD

**Issue by tomtau** [crypto-org-chain/chain-main#407]
Currently, one may need to jump through a few troubleshooting hoops

**Comment by yihuang** [comment]
I guess these are the main issues:
- Two shells:
  - The default `nix-shell` don't build `chain-maind` automatically, rather use the one in `PATH`.
    - `make build` put result in `./build` directory, need to put it in `PATH`, so the integration test in dev shell can find it.
  - The ci shell `nix-shell ./. -A ci-shell` will build the `chain-maind` automatically and find it by absolute path.
- set environment variable `TMPDIR=/tmp` in mac, to avoid path too long issue with unix socket.
- Suggest to use `direnv` to manage the environment variables.

**Comment by JayT106** [comment]
For the pytest,

I think it needs to install some python libraries for the test? 
pip install python-dateutil
pip install PyYaml
pip install ./pystarport

**Comment by yihuang** [comment]
With `nix-shell`, you don't need to install dependencies yourself.

**Comment by JayT106** [comment]
Sure, I will go through the setup again with a clear env. And then update the docs.
