### ISSUE TITLE
Problem: create-validator fails on windows with "Element not found"

### ISSUE THREAD

**Issue by dhinterlechner** [crypto-org-chain/chain-main#430]
**Describe the bug**
Trying to setup a validator on Windows 10 - but the create-validator step produces the error: Element not found. without further details.

**To Reproduce**
1. Follow the steps from https://crypto.org/docs/getting-started/mainnet.html#pre-requisites until Step 3-5
2. Try to execute the command  ./chain-maind tx staking create-validator [...]
3. see the error

![image](https://user-images.githubusercontent.com/43072243/112516034-24170a80-8d97-11eb-81c1-22e5751550f5.png)

**Expected behavior**
Beeing able to setup the validator

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows 10 20H2 64-bit
 - Browser [e.g. chrome, safari] - not relevant
 - Version [e.g. 22] 19042.867

**Comment by tomtau** [comment]
@leejw51crypto @lezzokafka can you reproduce this?

**Comment by dhinterlechner** [comment]
I installed the chain-maind on a fresh clean Windows installation without any other software - may be a dependencies problem?

**Comment by tomtau** [comment]
possible, but the binary should be statically compiled.
In the meantime, you can try using WSL:  https://docs.microsoft.com/en-us/windows/wsl/install-win10 + the Linux binary

**Comment by orfeas0** [comment]
Running the create-validator on linux returns:

`Error: rpc error: code = NotFound desc = account cro10mys3cr3t4address not found: key not found
`

More specifically:

```
chain-maind tx staking create-validator \
    --from=Default \
    --amount=1000cro \
    --pubkey=$(chain-maind tendermint show-validator) \
    --moniker="mymoniker" \
    --security-contact="my@email.com" \
    --chain-id="crypto-org-chain-mainnet-1" \
    --commission-rate="0.1" \
    --commission-max-rate="0.2" \
    --commission-max-change-rate="0.01" \
    --min-self-delegation="1" \
    --gas 8000000 \
    --gas-prices 0.1basecro \
    --dry-run
```
Tried to use both `Default` and `cro10mys3cr3t4address` as the --from field, the result is the same.

**Comment by dhinterlechner** [comment]
> **Describe the bug**
> Trying to setup a validator on Windows 10 - but the create-validator step produces the error: Element not found. without further details.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Follow the steps from https://crypto.org/docs/getting-started/mainnet.html#pre-requisites until Step 3-5
> 2. Try to execute the command  ./chain-maind tx staking create-validator [...]
> 3. see the error
> 
> ![image](https://user-images.githubusercontent.com/43072243/112516034-24170a80-8d97-11eb-81c1-22e5751550f5.png)
> 
> **Expected behavior**
> Beeing able to setup the validator
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]: Windows 10 20H2 64-bit
> * Browser [e.g. chrome, safari] - not relevant
> * Version [e.g. 22] 19042.867

Still persisting after upgrade to 1.2.0

**Comment by tomtau** [comment]
does that account have funds? you can try if it can be reproduced on the testnet with https://crypto.org/faucet -- https://crypto.org/docs/getting-started/croeseid-testnet.html (using this binary https://github.com/crypto-org-chain/chain-main/releases/tag/v0.9.1-croeseid )

**Comment by dhinterlechner** [comment]
> does that account have funds? you can try if it can be reproduced on the testnet with https://crypto.org/faucet -- https://crypto.org/docs/getting-started/croeseid-testnet.html (using this binary https://github.com/crypto-org-chain/chain-main/releases/tag/v0.9.1-croeseid )

I tryed, but at block height i get wrong Header

`←[90m8:04PM←[0m ←[32mINF←[0m starting ABCI with Tendermint
←[90m8:04PM←[0m ←[32mINF←[0m Starting multiAppConn service ←[36mimpl=←[0m{"Logger":{}} ←[36mmodule=←[0mproxy
←[90m8:04PM←[0m ←[32mINF←[0m Starting localClient service ←[36mconnection=←[0mquery ←[36mimpl=←[0m"marshaling error: json: unsupported type: abcicli.Callback" ←[36mmodule=←[0mabci-client
←[90m8:04PM←[0m ←[32mINF←[0m Starting localClient service ←[36mconnection=←[0msnapshot ←[36mimpl=←[0m"marshaling error: json: unsupported type: abcicli.Callback" ←[36mmodule=←[0mabci-client
←[90m8:04PM←[0m ←[32mINF←[0m Starting localClient service ←[36mconnection=←[0mmempool ←[36mimpl=←[0m"marshaling error: json: unsupported type: abcicli.Callback" ←[36mmodule=←[0mabci-client
←[90m8:04PM←[0m ←[32mINF←[0m Starting localClient service ←[36mconnection=←[0mconsensus ←[36mimpl=←[0m"marshaling error: json: unsupported type: abcicli.Callback" ←[36mmodule=←[0mabci-client
←[90m8:04PM←[0m ←[32mINF←[0m Starting EventBus service ←[36mimpl=←[0m{"Logger":{}} ←[36mmodule=←[0mevents
←[90m8:04PM←[0m ←[32mINF←[0m Starting PubSub service ←[36mimpl=←[0m{"Logger":{}} ←[36mmodule=←[0mpubsub
←[90m8:04PM←[0m ←[32mINF←[0m Starting IndexerService service ←[36mimpl=←[0m{"Logger":{}} ←[36mmodule=←[0mtxindex
←[90m8:04PM←[0m ←[32mINF←[0m ABCI Handshake App Info ←[36mhash=←[0mA3E55D61FD6A1D2B9B33C2EA938EFB7B7D097F604EB729324429DC90E10C371C ←[36mheight=←[0m116426 ←[36mmodule=←[0mconsensus ←[36mprotocol-version=←[0m0 ←[36msoftware-version=←[0m
←[90m8:04PM←[0m ←[32mINF←[0m ABCI Replay Blocks ←[36mappHeight=←[0m116426 ←[36mmodule=←[0mconsensus ←[36mstateHeight=←[0m116426 ←[36mstoreHeight=←[0m116427
←[90m8:04PM←[0m ←[32mINF←[0m Replay last block using real app ←[36mmodule=←[0mconsensus
Error: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected A3E55D61FD6A1D2B9B33C2EA938EFB7B7D097F604EB729324429DC90E10C371C, got ED6812F726581714F9659496D29071A5D8440B9F8A8D0FA0CF9BF6396069DC65`

Is the Croeseid Testnet still active? as the explorer seems to be also offline  https://crypto.org/explorer/croeseid/

**Comment by tomtau** [comment]
> > does that account have funds? you can try if it can be reproduced on the testnet with https://crypto.org/faucet -- https://crypto.org/docs/getting-started/croeseid-testnet.html (using this binary https://github.com/crypto-org-chain/chain-main/releases/tag/v0.9.1-croeseid )
> 
> I tryed, but at block height 116426 i get wrong Header
> 
> `←[90m8:04PM←[0m ←[32mINF←[0m starting ABCI with Tendermint ←[90m8:04PM←[0m ←[32mINF←[0m Starting multiAppConn service ←[36mimpl=←[0m{"Logger":{}} ←[36mmodule=←[0mproxy ←[90m8:04PM←[0m ←[32mINF←[0m Starting localClient service ←[36mconnection=←[0mquery ←[36mimpl=←[0m"marshaling error: json: unsupported type: abcicli.Callback" ←[36mmodule=←[0mabci-client ←[90m8:04PM←[0m ←[32mINF←[0m Starting localClient service ←[36mconnection=←[0msnapshot ←[36mimpl=←[0m"marshaling error: json: unsupported type: abcicli.Callback" ←[36mmodule=←[0mabci-client ←[90m8:04PM←[0m ←[32mINF←[0m Starting localClient service ←[36mconnection=←[0mmempool ←[36mimpl=←[0m"marshaling error: json: unsupported type: abcicli.Callback" ←[36mmodule=←[0mabci-client ←[90m8:04PM←[0m ←[32mINF←[0m Starting localClient service ←[36mconnection=←[0mconsensus ←[36mimpl=←[0m"marshaling error: json: unsupported type: abcicli.Callback" ←[36mmodule=←[0mabci-client ←[90m8:04PM←[0m ←[32mINF←[0m Starting EventBus service ←[36mimpl=←[0m{"Logger":{}} ←[36mmodule=←[0mevents ←[90m8:04PM←[0m ←[32mINF←[0m Starting PubSub service ←[36mimpl=←[0m{"Logger":{}} ←[36mmodule=←[0mpubsub ←[90m8:04PM←[0m ←[32mINF←[0m Starting IndexerService service ←[36mimpl=←[0m{"Logger":{}} ←[36mmodule=←[0mtxindex ←[90m8:04PM←[0m ←[32mINF←[0m ABCI Handshake App Info ←[36mhash=←[0mA3E55D61FD6A1D2B9B33C2EA938EFB7B7D097F604EB729324429DC90E10C371C ←[36mheight=←[0m116426 ←[36mmodule=←[0mconsensus ←[36mprotocol-version=←[0m0 ←[36msoftware-version=←[0m ←[90m8:04PM←[0m ←[32mINF←[0m ABCI Replay Blocks ←[36mappHeight=←[0m116426 ←[36mmodule=←[0mconsensus ←[36mstateHeight=←[0m116426 ←[36mstoreHeight=←[0m116427 ←[90m8:04PM←[0m ←[32mINF←[0m Replay last block using real app ←[36mmodule=←[0mconsensus Error: error during handshake: error on replay: wrong Block.Header.AppHash. Expected A3E55D61FD6A1D2B9B33C2EA938EFB7B7D097F604EB729324429DC90E10C371C, got ED6812F726581714F9659496D29071A5D8440B9F8A8D0FA0CF9BF6396069DC65`
> 
> Is the Croeseid Testnet still active? as the explorer seems to be also offline https://crypto.org/explorer/croeseid/

did you follow these instructions https://github.com/crypto-org-chain/testnets/blob/main/testnet-croeseid-2/croeseid-v0.9.1-fullnode.md ?

**Comment by dhinterlechner** [comment]
Yes, I can reproduce it on testnet. I investigated even further, running the command "./chain-maind keys add somename" generates the same error (both testnet and mainnet)

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
```
Error: The specified item could not be found in the keyring
Usage:
  chain-maind tx staking create-validator [flags]
```

it seems keyring error, try attach --keyring-backend file
for testnet-croeseid-2, don't use latest binary version.
use this version

https://github.com/crypto-org-chain/chain-main/releases/download/v0.9.1-croeseid/chain-main_0.9.1-croeseid_Windows_x86_64.zip

**Comment by dhinterlechner** [comment]
> ```
> Error: The specified item could not be found in the keyring
> Usage:
>   chain-maind tx staking create-validator [flags]
> ```
> 
> it seems keyring error, try attach --keyring-backend file
> for testnet-croeseid-2, don't use latest binary version.
> use this version
> 
> https://github.com/crypto-org-chain/chain-main/releases/download/v0.9.1-croeseid/chain-main_0.9.1-croeseid_Windows_x86_64.zip

Now the command ./chain-maind keys add somename creates some files and the ./chain-maind tx staking create-validator asks for the passphrase but afterwards it says 
`PS D:\testnet> .\chain-maind tx staking create-validator --from=tcro199k79v2ayr3n8h3l4ycfzufrlmpkj9yha9ht3f --amount=1tcro --pubkey=tcrocnclconspub1zcjduepq2gccadvz3mqxpqf66pnwyxryhhlkzhlkpk2zaqfjn0fkavzp2kwshm8zrh --moniker="daniel" --security-contact="chain@somedomain.eu" --website="https://chain.somedomain.eu" --chain-id="testnet-croeseid-2" --commission-rate="0.05" --commission-max-rate="0.2" --commission-max-change-rate="0.01" --min-self-delegation="1" --keyring-backend file
Enter keyring passphrase:
Error: rpc error: code = NotFound desc = account tcro199k79v2ayr3n8h3l4ycfzufrlmpkj9yha9ht3f not found: key not found
Usage:
  chain-maind tx staking create-validator [flags]`

created first the key with:

![testnet-2](https://user-images.githubusercontent.com/43072243/113330702-52f52980-931f-11eb-9f85-2aa9037ba31b.PNG)

**Comment by dhinterlechner** [comment]
After some try and error I was able to create both wallet and validator on CLI but only with ledger and the following commands:

`.\chain-maind tx staking create-validator --from=cro1nr..... --amount=1cro --pubkey=crocnclconspub......... --moniker="Node" --security-contact="chain@mail.somedomain.eu" --website="https://chain.somedomain.eu" --chain-id="crypto-org-chain-mainnet-1" --commission-rate="0.0099" --commission-max-rate="0.2" --commission-max-change-rate="0.01" --min-self-delegation="1" --ledger --keyring-backend file --gas auto --gas-adjustment=1.5 --gas-prices 0.1basecro`

` .\chain-maind keys add Validator --ledger --index 1 --keyring-backend file`

**Comment by tomtau** [comment]
> After some try and error I was able to create both wallet and validator on CLI but only with ledger and the following commands:

I assume this is all good -- so closing this issue for now, but feel free to reopen it
