### ISSUE TITLE
Problem: can´t Redelegate

### ISSUE THREAD

**Issue by Coyocon** [crypto-org-chain/chain-main#436]
I want to redelagete but show me a error "failed to execute message; message index: 0: redelegation to this validator already in progress; first redelegation to this validator must complete before next redelegation" but my older transacción have the same problem, so I don´t have a order of Redelegate , what can i do?

**Comment by tomtau** [comment]
@Coyocon using which wallet?

**Comment by Coyocon** [comment]
usign Ledger with Crypto  Desktop, because I don´t understand how to use Chain-main in delegate and redelegate

**Comment by lezzokafka** [comment]
Hello @Coyocon, may I ask if the fund has already been redelegated before? 
Would you mind to send me a DM on Discord channel with your `cro` address so that I have have a deeper look into that?

**Comment by tomtau** [comment]
may have been fixed with https://github.com/crypto-com/chain-desktop-wallet/pull/348 -- feel free to open an issue on chain-desktop-wallet if not
