### ISSUE TITLE
Problem: subscription module better to be implemented in smart contract

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/chain-main#451]
For example implement in CosmWasm.
Advantages:
- sandboxed execution environment
- builtin gas meter, no ddos vulnerability brought in by business code.
- better upgrade story

Issues:
- No begin blocker event to trigger automatic payment collection, need off-chain process to trigger periodically (similar to the role of relayer in ibc).

**Comment by tomtau** [comment]
"subscription module better to be implemented in smart contract" isn't a problem statement, but a solution statement 😁
given the lack of "begin blocker" in wasmd / cw, this may be a non-starter in the near future.

if you foresee some specific problems with the current subscription module, feel free to open issue(s) for them -- https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md#consensus-breaking-and-large-structural-code-changes -- once the problems are clear, we can document in ADR the proposed solution (e.g. remove the subscription module and introduce this functionality via CW when it becomes feasible in CW, ideally with a reference to the blocking CW issue/roadmap)
