### ISSUE TITLE
Problem: incompatible bech32 versions between pystarport and chainlibpy

### ISSUE THREAD

**Issue by CeruleanAtMonaco** [crypto-org-chain/chain-main#455]
**Describe the bug**
chainlibpy (1.0.1) depends on bech32 (>=1.1.0,<1.2.0)
   and pystarport (0.1.0) depends on bech32 (^1.2.0), chainlibpy (>=1.0.0,<2.0.0) is incompatible with pystarport (0.1.0).

**To Reproduce**
1. go to `integration_tests` folder
2. run `poetry update`
3. get error below
```
Updating dependencies
Resolving dependencies... (6.1s)

  SolverProblemError

  Because chainlibpy (1.0.0) depends on bech32 (>=1.1.0,<1.2.0)
   and no versions of chainlibpy match >1.0.0,<1.0.1 || >1.0.1,<2.0.0, chainlibpy (>=1.0.0,<1.0.1 || >1.0.1,<2.0.0) requires bech32 (>=1.1.0,<1.2.0).
  And because chainlibpy (1.0.1) depends on bech32 (>=1.1.0,<1.2.0)
   and pystarport (0.1.0) depends on bech32 (^1.2.0), chainlibpy (>=1.0.0,<2.0.0) is incompatible with pystarport (0.1.0).
  So, because integration-tests depends on both pystarport (0.1.0) and chainlibpy (^1.0.0), version solving failed.

```

**Expected behavior**
Expected to be able to upgrade dependencies for integration tests.

**Proposed solution**
Upgrade bech32 version in chainlibpy.

**Screenshots**
N/A

**Desktop (please complete the following information):**
macOS Big Sur (not that relevant thou)

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by tomtau** [comment]
https://github.com/crypto-org-chain/chainlibpy/commit/e922694326ee00b404622310170cb83969f0e993#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R39
I guess one solution is to update chainlibpy and publish a new version of chainlibpy, or just lower the dependency bounds in pystarport?

**Comment by yihuang** [comment]
I can't reproduce locally, and `integration_tests/poetry.lock` don't contains `chainlibpy`, are there other setups?
