### ISSUE TITLE
Problem: O(N) complexity in subscription module's begin block handler

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/chain-main#458]
Currently subscription module's begin block try to process all the subscriptions that need to be processed, which might cause sudden increase of overhead. For example, for some popular cron pattern like `@monthly`, many subscriptions will need to be processed at the same time.
Potential solution:
- limit the max number of subscriptions processed in each block.

**Comment by tomtau** [comment]
does the SDK's "distribution" module have the same problem (distributing rewards to validator-delegators)?

**Comment by yihuang** [comment]
> does the SDK's "distribution" module have the same problem (distributing rewards to validator-delegators)?

I think in begin block, it only accumulate rewards to the previous proposer, when delegator withdraw reward, it then calculate the amount for one delegator.

**Comment by tomtau** [comment]
Yeah, it does "lazy accounting"... that's probably not applicable here.
I guess one way to cap it here may be by "block max gas" parameter -- this would work better with https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-037-deliver-block.md

**Comment by tomtau** [comment]
`GasPerCollection / BlockMaxGas` ?

**Comment by yihuang** [comment]
> `BlockMaxGas / GasPerCollection ` ?

It'll take a pretty rough estimate to convert golang execution cost to gas number anyway, or we just make a rough estimate to the limit directly?

**Comment by yihuang** [comment]
> `BlockMaxGas / GasPerCollection ` ?

seems make sense.

**Comment by tomtau** [comment]
https://github.com/crypto-org-chain/chain-main/commit/428c6c73ece9f961e54dfa1159b015c0ae96afcb
https://github.com/crypto-org-chain/cosmwasm-plus-plus
