### ISSUE TITLE
Problem: simulations fail on the latest master

### ISSUE THREAD

**Issue by tomtau** [crypto-org-chain/chain-main#466]
It seems it's due to the subscriptions module: https://github.com/crypto-org-chain/chain-main/runs/2302153745#step:9:258 ?

**Comment by allthatjazzleo** [comment]
got the same error when run `make test-sim-nondeterminism` in local

It seems simulations started to fail since subscriptions module is added?
https://github.com/crypto-org-chain/chain-main/commit/22f169de62476433774c91f174f7ad107537929b

**Comment by yihuang** [comment]
I think it's because the [test function](https://github.com/crypto-org-chain/chain-main/blob/master/app/sim_test.go#L85) calls [`simapp.AppStateFn`](https://github.com/cosmos/cosmos-sdk/blob/master/simapp/state.go#L136) which don't generate state with subscription module.

**Comment by allthatjazzleo** [comment]
> I think it's because the [test function](https://github.com/crypto-org-chain/chain-main/blob/master/app/sim_test.go#L85) calls [`simapp.AppStateFn`](https://github.com/cosmos/cosmos-sdk/blob/master/simapp/state.go#L136) which don't generate genesis state containing subscription module.

@yihuang 
subscription module can be imported in [app.sm](https://github.com/crypto-org-chain/chain-main/blob/a16965edd5d6793d8136c7d4f3f96cc1d05ce920/app/app.go#L382)?

**Comment by yihuang** [comment]
> > I think it's because the [test function](https://github.com/crypto-org-chain/chain-main/blob/master/app/sim_test.go#L85) calls [`simapp.AppStateFn`](https://github.com/cosmos/cosmos-sdk/blob/master/simapp/state.go#L136) which don't generate genesis state containing subscription module.
> 
> @yihuang
> subscription module can be imported in [app.sm](https://github.com/crypto-org-chain/chain-main/blob/a16965edd5d6793d8136c7d4f3f96cc1d05ce920/app/app.go#L382)?

Not here, `simapp` is initiated in cosmos-sdk, to fix it, we might need to copy and modify `simapp/state.go` from cosmos-sdk repo.

**Comment by tomtau** [comment]
https://github.com/crypto-org-chain/chain-main/commit/428c6c73ece9f961e54dfa1159b015c0ae96afcb
https://github.com/crypto-org-chain/cosmwasm-plus-plus
