### ISSUE TITLE
Problem: Build status badge link error

### ISSUE THREAD

**Issue by y-luis** [crypto-org-chain/chain-main#474]
Project's Build Status Badge links to a page not found.

**To Reproduce**
1. Go to [chain-main repo](https://github.com/crypto-org-chain/chain-main)
2. Click on Build Status badge
3. Goes to a page not found (https://github.com/crypto-org-chain/chain-main/workflows)

**Expected behavior**
Open the corresponding workflow page.

**Comment by y-luis** [comment]
Working on a proposal.

**Comment by y-luis** [comment]
Proposal created with crypto-org-chain/chain-main#475

**Comment by tomtau** [comment]
thank you for your contribution!
