### ISSUE TITLE
Problem: minimal gas fee required in toml config

### ISSUE THREAD

**Issue by tomtau** [crypto-org-chain/chain-main#485]
> Marko  3:36 PM
> Hey, I was looking through your docs. The section for sed the minimum gas prices, you could avoid this by using the modular antehandler. In short if you write a custom antehandler (https://github.com/cosmos/cosmos-sdk/blob/master/x/auth/ante/ante.go) you can avoid using the minimum gas price section in the toml and possibly make it a global thing. Some ways this can be done is doing something like eip1559 or a param for the minimum fee. We dont have the best documentation on this front but its quite simple to accomplish.

**Comment by devashishdxt** [comment]
Link to documentation: 3rd step in https://crypto.org/docs/getting-started/mainnet.html#step-2-configure-chain-maind

**Comment by devashishdxt** [comment]
@tomtau Is there any reason why a separate `AnteHandler` is required? There's already a `AnteHandler` which reads the value from config and checks for minimum gas fee. https://github.com/cosmos/cosmos-sdk/blob/6ad84c5065ad50d6a2f1a2ee4f781d3fe68acf61/x/auth/ante/fee.go#L23

**Comment by tomtau** [comment]
@devashishdxt afaik @marbar3778 's suggestion was that if you wanted to avoid reading the config file value (i.e. have the value hardcoded or have it as a network parameter), this can be done with a separate `AnteHandler`

**Comment by tomtau** [comment]
maybe ok to keep it in the config
