### ISSUE TITLE
Problem: integration test takes too long time to complete

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/chain-main#489]
how about split into 2 or 3 yml
for example,
build1.yml, build2.yml, build3.yml
or some large category

and run simultaneously

**Comment by leejw51crypto** [comment]
divide into 2 or 3 steps

**Comment by leejw51crypto** [comment]
started

**Comment by yihuang** [comment]
> how about split into 2 or 3 yml
> for example,
> build1.yml, build2.yml, build3.yml
> or some large category
> 
> and run simultaneously

Do you mean multiple workflows runs in parallel?

**Comment by leejw51crypto** [comment]
yes

**Comment by leejw51crypto** [comment]
https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration

concurrent jobs table

**Comment by leejw51crypto** [comment]
separated into 3 jobs, and checking the speed now

**Comment by leejw51crypto** [comment]
![image](https://user-images.githubusercontent.com/51560997/121119941-2db8f600-c84f-11eb-8db2-73839493d0b7.png)

**Comment by leejw51crypto** [comment]
will change number to each step, will tidy up

**Comment by leejw51crypto** [comment]
![image](https://user-images.githubusercontent.com/51560997/121333784-ad2bef80-c94b-11eb-8bee-6429cbf0f023.png)

**Comment by leejw51crypto** [comment]
doing refactoring
