### ISSUE TITLE
Problem: ibc relayer setting is difficult

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/chain-main#490]
as client cli, add ibc relayer config generator, so any user can quickly set up ibc setup easily.

enter first chain-id?
enter first node url?
enter second chain-id?
enter second node url?

**Comment by tomtau** [comment]
Which relayer?
maybe the issue is better to be opened on https://github.com/confio/ts-relayer or https://github.com/informalsystems/ibc-rs
