### ISSUE TITLE
Problem: Unhelpful error message when incorrect voting option is given

### ISSUE THREAD

**Issue by regisd** [crypto-org-chain/chain-main#491]
**Describe the bug**
In gov module, the error message when the voting_option argument is not valid is not actionable.

**To Reproduce**
```
chain-maind tx gov vote 2 invalid_foo_bar  --from [key_name] --chain-id="crypto-org-chain-mainnet-1" --node https://mainnet.crypto.org:26657
```

**Expected behavior**
> Error: 'invalid_foo_bar' is not a valid vote option. \
> Valid value of "option" argument are: "yes", "no", "no_with_veto" or "abstain".

**Actual behaviour**
> Error: 'invalid_foo_bar' is not a valid vote option

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser N/A
 - Version: v1.1.0

**Additional context**
https://www.reddit.com/r/Crypto_com/comments/mvyqvj/ibc_governance_proposal_for_the_cryptoorg_chain/

**Comment by devashishdxt** [comment]
Created a PR: https://github.com/cosmos/cosmos-sdk/pull/9185

**Comment by regisd** [comment]
cosmos/cosmos-sdk#9185 was merged
