### ISSUE TITLE
Problem: missing consequences in ADR-001

### ISSUE THREAD

**Issue by tomtau** [crypto-org-chain/chain-main#492]
https://github.com/crypto-org-chain/chain-main/blob/master/doc/architecture/adr-001.md

A few missing consequences:
- state sync not working in the current version / blocked by Cosmos SDK
- Windows and Arm64 compilation not working / blocked by Wasmer

I guess the decision may also need to be updated -- e.g. the CosmWasm module to be added under a feature flag until this is resolved + the future testnet version instructions may need to instruct users not to use state sync? @yihuang @leejw51crypto

**Comment by leejw51crypto** [comment]
yes, m1 and windows should compile cosmwasm definitely.
state sync should include cosmwasm coded uploaded.

**Comment by pattarapon23** [comment]
Ok
