### ISSUE TITLE
Problem: missing support of RDBMS

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/chain-main#493]
add option to sync with external database
for example postgresql, mysql, etc.

for balance, validator query can be fast fetched from RDBMS.
only maintain one node which writes to RDBMS

this feature can be used for supporting non custodial wallets.
this issue will greatly improve backend speed

this issue can be submitted as cosmos-sdk pr.

**Comment by yihuang** [comment]
isn't it chain-indexing project?

**Comment by tomtau** [comment]
https://github.com/crypto-com/chain-indexing
+ @JayT106 is working on PR for Tendermint Core
