### ISSUE TITLE
Problem: missing support of displaying all addresses in bech32 format

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/chain-main#499]
add cli command to show all possible format from bech32 address
it would be convenient for users to handle addresses

delegator address
operator address
consensus node address (tendermint validator address)

1. receive address from any address address
2. display all with different hrp

**Comment by tomtau** [comment]
this feature is under "debug" command which allows converting between different bech32 hrp formats for pub keys and addresses
