### ISSUE TITLE
Problem: missing extended IBC integration tests

### ISSUE THREAD

**Issue by tomtau** [crypto-org-chain/chain-main#504]
- error cases with relayer failures
- 3 chain transfer (A,B)->C 1. A->C, 2. C->B

mentioned by @leejw51crypto

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
tested functions with testnet-croeseid-2
now adding to the integration test

**Comment by leejw51crypto** [comment]
testing scenario is ready
i'll code after this pr
https://github.com/crypto-org-chain/chain-main/issues/508

**Comment by leejw51crypto** [comment]
create nft, query done

**Comment by leejw51crypto** [comment]
burn, transfer done.
tidying up the source

**Comment by leejw51crypto** [comment]
continue

**Comment by leejw51crypto** [comment]
in code-review
