### ISSUE TITLE
Problem: simple NFT module not reviewed and tested

### ISSUE THREAD

**Issue by tomtau** [crypto-org-chain/chain-main#507]
https://github.com/irisnet/irismod/tree/master/modules/nft

open a PR to vendor in the code + add basic integration tests.

Optionally, a small enhancement may be added (e.g. network params to disable/enable individual functionality -- minting, burning, transfer, edit -- or restrict to the usage to a dedicated address)

**Comment by leejw51crypto** [comment]
i'll help the integration test
