### ISSUE TITLE
Problem: vendored NFT module's permissions are too lax

### ISSUE THREAD

**Issue by tomtau** [crypto-org-chain/chain-main#520]
> By default it will not fail if the transfer is executed by someone beside the owner. It is highly recommended that a custom handler is made to restrict use of this Message type to prevent unintended use.

The code seems to check for the owner==sender, but it allows the owner to modify the token content:

this should be modified to match similar business logic to CW721 (only the token issuer can edit and burn its tokens; the token owner can only transfer): spec + implementation need to be updated + integration tests for this expected logic

**Comment by devashishdxt** [comment]
@tomtau Can the issuer edit/burn the tokens they do not own (anymore, i.e., they transferred them to someone else)?

**Comment by devashishdxt** [comment]
> ## MsgMintNFT
>
> This message type is used for minting new tokens. If a new `NFT` is minted under a new `Denom`, a new `Collection` will also be created, otherwise the `NFT` is added to the existing `Collection`. If a new `NFT` is minted by a new account, a new `Owner` is created, otherwise the `NFT` `ID` is added to the existing `Owner`'s `IDCollection`. By default anyone can execute this Message type. **It is highly recommended that a custom handler is made to restrict use of this Message type to prevent unintended use.**

Only the `creator` of the `Denom` should be able to mint new NFTs? @tomtau @yihuang @leejw51crypto

**Comment by tomtau** [comment]
@devashishdxt AFAIK yes, this is how it works in CW1155: https://github.com/CosmWasm/cosmwasm-plus/blob/main/contracts/cw1155-base/src/contract.rs#L211
