### ISSUE TITLE
Problem: Use of deprecated golangci-lint linters

### ISSUE THREAD

**Issue by devashishdxt** [crypto-org-chain/chain-main#530]
Following two linters are deprecated:

- [`interfacer`](https://github.com/mvdan/interfacer): deprecated
- [`scopelint`](https://github.com/kyoh86/scopelint): obsoleted (replaced by [`exportloopref`](https://github.com/kyoh86/exportloopref))

**Comment by yihuang** [comment]
I think the current `.golangci.yml` is adopted from cosmos-sdk, maybe we should update.

**Comment by tomtau** [comment]
I guess if the golangci config is adjusted, those lint suppressions for interfacer can be removed
