### ISSUE TITLE
Problem: nft denomid, tokenid max length is too small

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/chain-main#546]
if denomid contains hex of sha256, it is more than 64 characters

Error: the length of denom(mytoken677578fa480df7daa517233a6a8ac2ec5a5b88eec9a32e1764574bf97c140ffd) only accepts value [3, 64]: invalid denom

also special characters such "/" would be handy

for denomid, tokenid
how about make it the same with ibc denom length?

**Comment by devashishdxt** [comment]
We cannot use `/` because it is used as a separator in key store.

**Comment by leejw51crypto** [comment]
how about _

**Comment by calvinaco** [comment]
There are a few rules in the current implementation, maybe we can take this opportunity to re-visit and see which need to keep or change.

1. [3, 63] character length check
2. Alpha-numeric only
3. Must being with alphabet

**Comment by leejw51crypto** [comment]
apply in cosmwasm

**Comment by tomtau** [comment]
> apply in cosmwasm

just more context for the future reference -- this was also discussed on Slack:
* current rules are restrictive, but should be all right (e.g. the major use case for collectibles plans to use UUIDs which are 128bit, i.e. 32 chars in hexadecimal)
* there's already a testnet binary released
* the goal is to keep this simple -- ideally the module will be migrated to the official/standard SDK one once it exists -- if the official module keeps the original restrictive id validation rules and here it is made more flexible, it'll be harder to migrate to it

For other use cases and more flexibility, one can go with CosmWasm (CW721 or CW1155) in the future
