### ISSUE TITLE
Problem: sign-batch doesn't list signed txs

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/chain-main#551]
sign-batch only displays signatures
make it display all tx list which contains auth info, signature, so that
it can be used for broadcasting

**Comment by esspam** [comment]
I used the flag ```--signature-only=false``` in my tx-spamming-script. Is that maybe what you are searching for?

**Comment by leejw51crypto** [comment]
i'll try that @esspam

**Comment by leejw51crypto** [comment]
thanks @esspam 
it solved the problem ^^;
