### ISSUE TITLE
Problem: pystarport don't have standalone repository

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/chain-main#555]
Since `pystarport` can be used as a standalone tool, and not limited to crypto chain, but also supports other cosmos chains.
It would be good to move it to standalone repository, and released separately from chain-maind.

**Comment by leejw51crypto** [comment]
yes, also consider adding networking support.
so that it can be used for multiple devices setup

detecting peer by upnp

**Comment by MillyMil8732** [comment]
Can someone do it for me im completelylost

**Comment by yihuang** [comment]
> Can someone do it for me im completelylost

https://github.com/yihuang/pystarport
created here for now, will fork into crypto-org-chain org.

**Comment by leejw51crypto** [comment]
is this resolved?

**Comment by yihuang** [comment]
> is this issue resolved?

repo is here https://github.com/crypto-com/pystarport, just waiting for security team to review to go public.

**Comment by yihuang** [comment]
> is this issue resolved?

now the separate repo is ready, we can start removing the pystarport in this repo now.

**Comment by leejw51crypto** [comment]
i'll change to use separate repo

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
separated and tidy up now
