### ISSUE TITLE
Trying to get the out to get my funds back to my mcb wallet this is transactioncro14cq4jeh7wt5yfty3m66u42ufdatukce5skxzmy

### ISSUE THREAD

**Issue by ajedwards3738** [crypto-org-chain/chain-main#558]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ajedwards3738** [comment]
I want y'all to help me get my funds back to my mcb wallet ( crypto.com(.    cro14cq4jeh7wt5yfty3m66u42ufdatukce5skxzmy

**Comment by tomtau** [comment]
The description doesn't provide many details and it doesn't look like an issue related to the chain-main code itself -- if it is, feel free to reopen the issue.
Otherwise, you can try asking on the developer community Discord channels: https://discord.gg/pahqHz26q4
