### ISSUE TITLE
Problem: missing query for denom-names

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/chain-main#563]
denom-name is not subordinate key of denomid.
denomid ,
denomname,
are both primarykey, indenpendent

so add these commands)
chain-maind query nft denomname   <- query unique denomname
chain-maind query nft denomnames  <- query all denomnames with pagination

currently issuing
mydenomid, mydenomname
mydenomid2, mydenomname

issuing nft with above pattern is not possible.

so further nft handling can cause mistakes

```
{"height":"26","txhash":"415811AB980342625E4D315879F0F76BEE035C215E3CB5C01BFF9FB403B06052","codespace":"nft","code":9,"data":"","raw_log":"failed to execute message; message index: 0: denomName mydenomname has already exists: invalid denom","logs":[],"info":"","gas_wanted":"200000","gas_used":"58907","tx":null,"timestamp":""}
```

**Comment by devashishdxt** [comment]
> chain-maind query nft denomnames <- query all denomnames with paginatio

This already exists: `chain-maind query nft denoms`
Is there something else that we need to support @leejw51crypto?

**Comment by leejw51crypto** [comment]
that's for denomids.
we need to add for denom names

**Comment by leejw51crypto** [comment]
also rpc end points as well.

**Comment by devashishdxt** [comment]
> that's for denomids.
> we need to add for denom names

`chain-maind query nft denoms` queries details for all denoms including ID, name, etc. https://github.com/crypto-org-chain/chain-main/blob/aa2561b0404d51bb0140c21ed621694f240e1dbe/proto/nft/v1/query.proto#L36

**Comment by leejw51crypto** [comment]
yes, agree
only query by denomname
