### ISSUE TITLE
Problem:  only supporting interactive for mnemonics recover

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/chain-main#569]
currently to restore from mnemonics
```
chain-maind keys add test --recover
```
then user can enter mnemonics

this can be automated by giving mnemonics directly as an argument.
like this
```
chain-main keys add test --recover-mnemonics ".....mnemonics" 
```
this will be useful to integration test and development.
this issue can be submitted to cosmos-sdk directly.

**Comment by tomtau** [comment]
I think the purpose is to prevent mnemonics to be logged in the command line history.
for automation, one can use pipes or `expect`: https://linux.die.net/man/1/expect
