### ISSUE TITLE
Problem: missing feature of log re-direction

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/chain-main#570]
when run the chain-main,
many logs are displayed to the console.

if we can redirect display to the file, it would be handier for processing the log.
also user just run`tail` command to view the log

this feature can be added as a flag, default would be console output

**Comment by eeldivad** [comment]
Can we also have option to rotate logs so they don't grow too large?  Also an option to keep a set number of log files so we never have to worry about cleaning up old log files.  Perhaps the following flags

rotate_logs_size = 10mb
keep_log_files = 5

So it will generate new log files when it reaches 10mb and only keep the last 5 log files.

**Comment by devashishdxt** [comment]
https://12factor.net/logs

**Comment by devashishdxt** [comment]
@leejw51crypto What is the advantage of adding this feature in `chain-maind`? There are already many open-source projects that can do this.

**Comment by tomtau** [comment]
if one runs it as a systemd service, it will be automatically stored in a journal file. As for:

> if we can redirect display to the file, it would be handier for processing the log.
> also user just runtail command to view the log

one can then simply use `journalctl -u service-name -f`? @leejw51crypto

**Comment by tomtau** [comment]
one can configure log rotation etc. with systemd as well

**Comment by eeldivad** [comment]
I run on Windows so no easy way to log rotate if I redirect stdout to a file.  So my logs will just grow overtime unless I restart the chain-maind service, rename the log file and start it up again.  Uptime is crucial on this chain as we're penalized ranking for it.  If there are some free software out there that works for Windows please advise.  I haven't found one yet.  Thank you.

**Comment by tomtau** [comment]
@eeldivad https://serverfault.com/questions/358172/equivalent-of-logrotate-for-windows

**Comment by tomtau** [comment]
In general, the log management seems to be a common well-addressed problem, so this is likely not an issue for chain-main -- it may, however, be worth documenting some reliable setups for different platforms in chain-docs: https://github.com/crypto-org-chain/chain-docs so feel free to open log management-related documentation issues or PRs there
