### ISSUE TITLE
Problem: no one-key fullnode setup docker image

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/chain-main#579]
we already have a nix package(chain-utils-mainnet) that contains a one-key setup script, package binary and script together in docker image, do mainnet initialization automatically.
end user start full node by simply:
```
$ docker run some-image
```

**Comment by Victoryfan** [comment]
When I do ./chain-maind start, the data is in the /root/.chain-maind, how can change the position of the .chain-maind?

**Comment by yihuang** [comment]
> When I do ./chain-maind start, the data is in the /root/.chain-maind, how can change the position of the .chain-maind?

`chain-maind start --home /path/to/data`

**Comment by Victoryfan** [comment]
> > When I do ./chain-maind start, the data is in the /root/.chain-maind, how can change the position of the .chain-maind?
> 
> `chain-maind start --home /path/to/data`
Get it.

**Comment by Victoryfan** [comment]
Does the api port is 26657? Is there curl command to use?

**Comment by Victoryfan** [comment]
Does the api port is 26657? Is there curl command to use?

**Comment by lezzokafka** [comment]
> Does the api port is 26657? Is there curl command to use?

by default, the 26657 is the RPC Endpoint, for example 
`curl -s "http://localhost:26657/block?height="`  should show you the latest block

**Comment by Victoryfan** [comment]
Could you provide docker to run the node?

**Comment by yihuang** [comment]
> Could you provide docker to run the node?

If what you want is just a docker image contains the chain binary, can you build on like this?
```
FROM <any linux image>
COPY <chainmaind x64 Linux binary>
RUN <chainmaind commands>
```

**Comment by Victoryfan** [comment]
I build the dockerfile success.

**Comment by Victoryfan** [comment]
Now the version 1.2.1 sync to this height. I don't upgrade it. When should I upgrade it?
![image](https://user-images.githubusercontent.com/25604389/121675937-a4235580-cae6-11eb-8ccc-5fbd7b16a269.png)

**Comment by lezzokafka** [comment]
> Now the version 1.2.1 sync to this height. I don't upgrade it. When should I upgrade it?
> ![image](https://user-images.githubusercontent.com/25604389/121675937-a4235580-cae6-11eb-8ccc-5fbd7b16a269.png)

The upgrade height for `v1.2.1` to `v2.0.1` should be `922363`

**Comment by Victoryfan** [comment]
How can I upgrade it?

**Comment by lezzokafka** [comment]
> How can I upgrade it?

https://crypto.org/docs/getting-started/upgrade_guide.html#the-canis-major-upgrade-guide-v1-to-v2-0-1
This guide should be helpful once your node reached the block height `922363` .

**Comment by Victoryfan** [comment]
Hello, we use this command:curl -s "http://10.1.19.200:7013/block/latest", it returns: 404 page not found. But use your ip can get result.

**Comment by Victoryfan** [comment]
Can't I use this style in our node?

**Comment by Victoryfan** [comment]
This https://mainnet.crypto.org:1317/blocks/latest can get result, but our can't.

**Comment by yihuang** [comment]
> Hello, we use this command:curl -s "http://10.1.19.20:7013/block/latest" in our node, it returns: 404 page not found. But use your ip can get result.

this is the api server, you need to make sure `api.enabled = true` in `app.toml`, and the `api.address` is correct.

**Comment by tomtau** [comment]
It seems this issue is stale, but feel free to reopen it
