### ISSUE TITLE
Problem: Error during Handshake; Wrong Block.Header.AppHash

### ISSUE THREAD

**Issue by Zboi04** [crypto-org-chain/chain-main#582]
(This may not be a bug. I'm probably just missing something in plain sight) The other day I just configured chain-maind onto Ubuntu and started the Full Node process (Version 1.2.1). FYI I enabled state-sync. It was syncing up to the block accurately and quickly, but I decided to stop the process so that I could run the create-validator command. But before I did that, I wanted to run the node again to make sure everything was working fine. I started the node, but once it attempted to commit to its first block, an error occurred. I tried upgrading to version 2.0.1 to solve the issue, but that also didn't work. I then uninstalled Ubuntu and reinstalled it. I set up the node again, and it worked. But once I stopped it and tried running it again, I got the same error: **Error: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected FB26CF278A73E32C4712A748D7B22EB87F699F1BD53EF80D1961E02661305542, got A4934EE7E196CABD11124CDED21F0E0A7291E77CFF25907232946FE7FB3F79DB**

![Screenshot (3)_LI](https://user-images.githubusercontent.com/85850134/122450720-f2b07400-cf6c-11eb-9c72-8034531b6213.jpg)

Device Info:
-Windows 10 Version	10.0.19043 Build 19043
-Using WSL 2
-Using Ubuntu Ubuntu 20.04.2 LTS

**Comment by tomtau** [comment]
> FYI I enabled state-sync. It was syncing up to the block accurately and quickly, but I decided to stop the process so that I could run the create-validator command. 

@Zboi04 thank you for the report.

> FYI I enabled state-sync. It was syncing up to the block accurately and quickly, but I decided to stop the process so that I could run the create-validator command.

1) did you state-synced with 1.2.1 to some post-upgrade block height? That could be an issue.
2) how did you stop the process? e.g. stopping it with SIGKILL could cause an issue

**Comment by Zboi04** [comment]
I stopped the process using control c. After I got the node started for a second time, I used control z to suspend the node, and then  I tried starting it back up again, but I got the same error. It may be possible to reproduce the issue. Try installing and configuring chainmaind onto a different Ubuntu profile (or whatever you are using to run the node) with state sync turned on and press control c after it's synced up, then start it back up again.

**Comment by Zboi04** [comment]
It is possible that I state synced with to some post-upgrade block height, but I ran the node again without state sync (on 1.2.1), and I still got the same issue. So could it still be a post-upgrade block height issue?

**Comment by tomtau** [comment]
> It is possible that I state synced with to some post-upgrade block height, but I ran the node again without state sync (on 1.2.1), and I still got the same issue. So could it still be a post-upgrade block height issue?

Yes, it looks like it

**Comment by Zboi04** [comment]
I can now confirm it was a post-upgrade block height
