### ISSUE TITLE
Problem: missing warning of "TMPDIR"

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/chain-main#590]
when "TMPDIR" env-variable is not set, display warning in pystarport integration test
```
export TMPDIR=/tmp
and try again
```

**Comment by tomtau** [comment]
not sure if a duplicate of https://github.com/crypto-org-chain/chain-main/issues/588 ?

**Comment by leejw51crypto** [comment]
consider applying in ci-shell

**Comment by leejw51crypto** [comment]
this is the same with #588, close the issue
