### ISSUE TITLE
https://github.com/crypto-org-chain/chain-main/tree/master/x%2Fnft%2Fspec

### ISSUE THREAD

**Issue by baldFun50** [crypto-org-chain/chain-main#597]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tomtau** [comment]
https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md#feature-requests-and-bug-reports

**Comment by baldFun50** [comment]
No project
