### ISSUE TITLE
T

### ISSUE THREAD

**Issue by saed219** [crypto-org-chain/chain-main#601]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saed219** [comment]
[]()

**Comment by tomtau** [comment]
https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md#feature-requests-and-bug-reports
