### ISSUE TITLE
Problem: While parsing config: invalid character '/' looking for beginning of object key string

### ISSUE THREAD

**Issue by valchonedelchev** [crypto-org-chain/chain-main#605]
Fresh installation fails with the following error:
`Error: While parsing config: invalid character '/' looking for beginning of object key stringFresh install `

I have followed [the instructions](https://crypto.org/docs/getting-started/mainnet.html#step-1-get-the-crypto-org-chain-mainnet-binary) to download the binary, tried all the options bet the result is the same. Whatever I type all I get is this error.

I double checked all the configuration files under the `~/.chain-maind` and all the JSON files are valid.

<img width="969" alt="Screenshot 2021-07-23 at 06 53 49" src="https://user-images.githubusercontent.com/145162/126742295-a0dfc54e-c4f5-4e23-b15e-795a3be456b4.png">

I am not sure how to figure out where does this '/' comes from.

**Comment by tomtau** [comment]
it seems this issue may not be relevant on the latest releases, but feel free to reopen it if it is
