### ISSUE TITLE
Tansfer to crypto.com app

### ISSUE THREAD

**Issue by Ricejames676** [crypto-org-chain/chain-main#608]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [.I can figure put how to trade properly or transfer my crypto to the crypto.com app or the defi wallet without getting lost 1000 times ..]

I'd like to be able to enter the chain and see what I have and if I'm able to transfer it to something more easily that I'm familiar with, I'd use the chain way more than necessary. 

**Describe alternatives you've considered**
A great alternative would be to have every xrypto wallet that the customers have availableto be able tobe linked together and certain things be automatically transferred to the one of our choice. It could even just be visible in the wallet that are connected and we have the choice to push confirm in which ever wallet.

**Additional context**

**Comment by 100hp4ever** [comment]
confused uga buga

**Comment by tomtau** [comment]
this doesn't look like an issue with the chain-main application itself, but perhaps one of the end user wallets -- if it's regarding the desktop wallet, you can directly open issue here: https://github.com/crypto-com/chain-desktop-wallet/issues/new/choose
