### ISSUE TITLE
Problem: 3.0 is not released yet

### ISSUE THREAD

**Issue by 100hp4ever** [crypto-org-chain/chain-main#631]
The release tag is created but 3.0 is still not released. There is no need to wait.
Please fix the issue on mainnet.

**Comment by 100hp4ever** [comment]
It needs to be released asap

**Comment by eeldivad** [comment]
They are working as fast as they can.  What in this release are you most excited about?

**Comment by tomtau** [comment]
it's marked as a pre-release for now as it's pending tests and documentation. including upgrade instructions -- @lezzokafka @aw126 will later post an announcement with details on https://github.com/crypto-org-chain/chain-main/discussions/categories/announcements
