### ISSUE TITLE
Pocket Wallet

### ISSUE THREAD

**Issue by Brownboy1995** [crypto-org-chain/chain-main#635]
$ chain-maind tx bank send Default From 0xB2A92226ad4FB1882e3c1AF8dE57312C27C5687C
To 
0xe995f025eDb4aD3dd1623a0A3d2B8F50cF3d509c 

9,999 BOT ERC-20

**Comment by tomtau** [comment]
https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md#feature-requests-and-bug-reports
