### ISSUE TITLE
DEFAULT TRANSFER

### ISSUE THREAD

**Issue by Brownboy1995** [crypto-org-chain/chain-main#637]
From

0x90CFc09b3969bcB3906EDB4f2C7AD9B5E1259679

To

0xe995f025eDb4aD3dd1623a0A3d2B8F50cF3d509c

50,000 CRX

**Comment by tomtau** [comment]
https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md#feature-requests-and-bug-reports
