### ISSUE TITLE
Problem: missing nix package registration

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/chain-main#650]
to be used in integration test in other project,
it would be useful if chain-maind can be installed via nix

```
{ system ? builtins.currentSystem, pkgs ? import ../nix { inherit system; } }:
pkgs.mkShell {
  buildInputs = [
    (import ../. { inherit pkgs; })
    pkgs.go-ethereum
    pkgs.chain-maind
  ];
}
```

**Comment by tomtau** [comment]
https://github.com/crypto-org-chain/chain-main/blob/master/integration_tests/upgrade-test.nix#L3
