### ISSUE TITLE
I cant withdraw my funds!

### ISSUE THREAD

**Issue by Billy203** [crypto-org-chain/chain-main#687]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tomtau** [comment]
https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md#feature-requests-and-bug-reports

> In an issue, please describe what you did, what you expected, and what happened instead.
