### ISSUE TITLE
Problem: `x/supply` is not marked as deprecated

### ISSUE THREAD

**Issue by devashishdxt** [crypto-org-chain/chain-main#720]
As discussed in #716, we can deprecate `x/supply` module and eventually remove it when an alternate way to query liquid supply is available (either via cosmos-sdk's native module or chain-indexer).

Ref: https://github.com/protocolbuffers/protobuf/issues/1734#issuecomment-662623725

- [x] Write an ADR (#723)
- [ ] Implement changes (#724)

**Comment by tomtau** [comment]
and add an entry to https://github.com/crypto-org-chain/chain-main/tree/master/doc/architecture for the decision?

**Comment by devashishdxt** [comment]
> and add an entry to https://github.com/crypto-org-chain/chain-main/tree/master/doc/architecture for the decision?

Sure. I'll create an ADR and add an entry there.
