### ISSUE TITLE
Problem: Undecided `AllowMessages` for interchain accounts 

### ISSUE THREAD

**Issue by devashishdxt** [crypto-org-chain/chain-main#726]
Interchain accounts module has an ability to specify the message type or transactions that interchain accounts are authorised to execute. This issue is just for discussion around it and reaching a conclusion on which message types should be enabled for interchain accounts on `chain-main`

Ref: https://github.com/cosmos/ibc-go/blob/main/docs/apps/interchain-accounts/parameters.md#allowmessages

@tomtau @yihuang @calvinaco 

Please add your recommendations in the comments.

For me, `/cosmos.bank.v1beta1.MsgSend` is a no-brainer. But, do we also want to allow staking or governance related messages?

**Comment by tomtau** [comment]
@devashishdxt I think staking will be important for liquid staking-related use cases + possibly for that "key rotation" use case via solo machines.

gov should be there as well -- or if not gov, then authz

**Comment by devashishdxt** [comment]
List of `AllowMessages` in cosmos hub: https://github.com/cosmos/gaia/blob/f71a4be8b43c9891a36edbd365a5f3e8403da769/app/app.go#L639

**Comment by devashishdxt** [comment]
Current PR to enable interchain accounts uses list similar to cosmos hub except for tendermint related messages: https://github.com/crypto-org-chain/chain-main/pull/732

**Comment by calvinaco** [comment]
On a second thought, I think we can also add the authz messages too. This could potentially help with some advance liquid staking.

**Comment by calvinaco** [comment]
On a second thought, I think we can also add the authz messages too. This could potentially help with some advance liquid staking.
