### ISSUE TITLE
Problem: compile error in freebsd

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/chain-main#727]
when trying to compile on freebsd
```
cmd/chain-maind/app/app.go:207:10: undefined: WriteFile
```

go version: go version go1.17.5 freebsd/amd64
free bsd:  13.0-RELEASE

**Comment by leejw51crypto** [comment]
in appunix.go 
//go:build linux || darwin || freebsd
// +build linux darwin freebsd

**Comment by devashishdxt** [comment]
@leejw51crypto Can you create a PR for this? I don't have a freebsd os setup, so can't test it.

**Comment by tomtau** [comment]
FreeBSD isn't an officially supported target for now, so will close this issue, but feel free to open a PR with a fix

**Comment by Kevinkall** [comment]
cro1x0j3ywpdxskm8mlxyvlqwj6ljxqljaygsf5m68
