### ISSUE TITLE
Problem: Undecided default `TimeoutDuration` for interchain account packets

### ISSUE THREAD

**Issue by devashishdxt** [crypto-org-chain/chain-main#731]
Currently, the default `TimeoutDuration` for interchain account packets (when sending a transaction to host chain on behalf of interchain account) is 5 minutes (which can be overridden by the caller). Since interchain accounts use ordered channels, the channel will close if any packet times out. 5 minutes is a safe duration for relaying packets.

There are four options:

1. Keep default timeout to 5 minutes
2. Change default timeout to some other value
3. Remove the default timeout and make it mandatory for the caller to provide it in request.
4. Add `DefaultTimeoutDuration` to `icaauth` params so that it can be configured and changed in future.

@tomtau @yihuang @calvinaco Please provide your inputs in comments.

**Comment by tomtau** [comment]
@allthatjazzleo what was the longest delay for acking ics20?

**Comment by tomtau** [comment]
@devashishdxt should the value also be meant as a minimum? if someone puts a smaller timeout that could happen, it'll close a channel?

**Comment by devashishdxt** [comment]
> @devashishdxt should the value also be meant as a minimum? if someone puts a smaller timeout that could happen, it'll close a channel?

Yes. If someone puts a smaller timeout, then the channel may close if the packet times out. I think it is a good idea to make this as a `MinimumTimeoutDuration`. Should we return an error when the caller provided timeout duration is smaller than this? Also, if the caller doesn't provide any timeout duration, should this be treated as default or an error should be returned?

**Comment by tomtau** [comment]
how is it done in other ibc modules? maybe good to keep it consistent?

**Comment by devashishdxt** [comment]
> how is it done in other ibc modules? maybe good to keep it consistent?

Current default for `transfer` module in `ibc-go` is `10 minutes`. https://github.com/cosmos/ibc-go/blob/dbd2df26e54f17f94a498d3fe048d68df04735b6/modules/apps/transfer/types/packet.go#L21

`transfer` module completely disables the timeout if it is set to zero. But, I don't think that is possible for us to do here because `ica` module uses ordered channels.

**Comment by tomtau** [comment]
and other ibc apps? not sure if there's one more that also uses ordered channels?

**Comment by devashishdxt** [comment]
> and other ibc apps? not sure if there's one more that also uses ordered channels?

I'm not aware of any IBC apps other than transfer and interchain accounts.

**Comment by calvinaco** [comment]
Because of the nature of ordered channel, summarizing the above comment, how about:

1. MsgSubmitTx continue to accept a user timeout
2. If not specified, timeout set to `DefaultTimeoutDuration`, say 1 hour to be safe?
3. If the timeout is lower than `MinTimeoutDuration`, say 10mins, it is rejected?

**Comment by tomtau** [comment]
or for non-specified, just set to `MinTimeoutDuration`, so that there's only one parameter?
(assuming channel closing only affects one account and reopening isn't an issue)
