### ISSUE TITLE
how to enable websocket?

### ISSUE THREAD

**Issue by qinxg** [crypto-org-chain/chain-main#742]
app.toml can't find websocket 
How do I open it webscoket rpc?

**Comment by devashishdxt** [comment]
Hi @qinxg. I'm assuming that you want to open tendermint RPC websocket. The port for that is same as `rpc` port in `config.toml`. Here's the documentation for tendermint RPC: https://docs.tendermint.com/v0.34/rpc/

I'm closing this issue for now. Please feel free to reopen if you still need help.
