### ISSUE TITLE
Problem: ica test fails on main

### ISSUE THREAD

**Issue by tomtau** [crypto-org-chain/chain-main#766]
https://github.com/crypto-org-chain/chain-main/runs/6445725049?check_suite_focus=true

**Comment by devashishdxt** [comment]
I tested this locally and it works fine. Maybe we need to upgrade `hermes` version in integration tests?

**Comment by devashishdxt** [comment]
We'll anyway have to upgrade `hermes` for fee middleware integration tests.

**Comment by tomtau** [comment]
on the PR, it ran fine I think... so it may be that the test is unstable for some reason

**Comment by devashishdxt** [comment]
It failed on the PR after the last commit (where I add fee middleware in ICA controller keeper). https://github.com/crypto-org-chain/chain-main/pull/763/commits/78391317994774ee668f5862260d1ff9d49ee2bb

**Comment by tomtau** [comment]
oh, my mistake
