### ISSUE TITLE
Problem: Latest `hermes` is not used in integration tests

### ISSUE THREAD

**Issue by devashishdxt** [crypto-org-chain/chain-main#768]
In our integration tests, we use a very old version of `hermes` (0.5?). Upgrade it to latest version, i.e., [`v0.14.1`](https://github.com/informalsystems/ibc-rs/releases/tag/v0.14.1).

**Comment by Klion144** [comment]
Kindly open this live chat link to talk to the customer care directly on your issue https://direct.lc.chat/14174505/
