### ISSUE TITLE
Crowantgo440.

### ISSUE THREAD

**Issue by Mikec90** [crypto-org-chain/chain-main#777]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [I can’t download the files for the Crypto.org chain..]

**Describe the solution you'd like**
Download…
**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. GitHub Crypto.com Respiratory.

**Additional context**

**Comment by Klion144** [comment]
Kindly open this live chat link to talk to the customer care directly on your issue https://direct.lc.chat/14174505/

**Comment by tomtau** [comment]
> I can’t download the files for the Crypto.org chain..]

they can be downloaded on the Release page -- see: https://github.com/crypto-org-chain/chain-main/releases/tag/v3.3.3
