### ISSUE TITLE
Problem: released binary don't contain needed dynamic libraries

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/chain-main#781]
After [integrating cosmwasm](https://github.com/crypto-org-chain/chain-main/pull/780), the `chain-maind` binary will require the `libwsamvm.[so|dylib]` to run, it would be good to include the dynamic libraries inside the released bundle.

Solution:
- Adopt the [nix bundle solution used in cronos](https://github.com/crypto-org-chain/cronos/pull/476)

- [x] #793 linux, x86-64 mac
- [ ] TODO arm mac
- [ ] TODO windows

**Comment by tomtau** [comment]
will also need to bundle the Windows DLL

**Comment by devashishdxt** [comment]
We don't need this anymore. Closing.
