### ISSUE TITLE
Problem: `cosmos-sdk` is not updated to `v0.46`

### ISSUE THREAD

**Issue by Terra854** [crypto-org-chain/chain-main#823]
Version 0.46 of cosmos-sdk has been released. Therefore, i would like to propose that the project's cosmos-sdk be updated asap while v4 is still in alpha. That way, we will be able to implement minimum commissions which has been requested by multiple validators for a long time now.

**Comment by yihuang** [comment]
Should be similar to the cronos upgrade: https://github.com/crypto-org-chain/cronos/pull/578
The main blocker right now is: https://github.com/cosmos/ibc-go/pull/1653

**Comment by devashishdxt** [comment]
> Should be similar to the cronos upgrade: [crypto-org-chain/cronos#578](https://github.com/crypto-org-chain/cronos/pull/578) The main blocker right now is: [cosmos/ibc-go#1653](https://github.com/cosmos/ibc-go/pull/1653)

Also, `wasmd` needs to upgrade to `cosmos-sdk v0.46`.

**Comment by tomtau** [comment]
https://github.com/crypto-org-chain/chain-main/pull/828
