### ISSUE TITLE
# [Codecov](https://codecov.io/gh/crypto-org-chain/chain-main/pull/857?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=crypto-org-chain) Report

### ISSUE THREAD

**Issue by Anastasia1510** [crypto-org-chain/chain-main#859]
# [Codecov](https://codecov.io/gh/crypto-org-chain/chain-main/pull/857?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=crypto-org-chain) Report
> Merging [#857](https://codecov.io/gh/crypto-org-chain/chain-main/pull/857?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=crypto-org-chain) (c9e212d) into [master](https://codecov.io/gh/crypto-org-chain/chain-main/commit/83212f40ed0cad289487b402b5aec6d9f1671254?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=crypto-org-chain) (83212f4) will **decrease** coverage by `2.30%`.
> The diff coverage is `n/a`.

```diff
@@            Coverage Diff             @@
##           master     #857      +/-   ##
==========================================
- Coverage   18.88%   16.57%   -2.31%     
==========================================
  Files          92       91       -1     
  Lines       11896    11653     -243     
==========================================
- Hits         2246     1931     -315     
- Misses       9168     9267      +99     
+ Partials      482      455      -27     
```

| Flag | Coverage Δ | |
|---|---|---|
| integration_tests | `16.57% <ø> (ø)` | |
| unit_tests | `?` | |

Flags with carried forward coverage won't be shown. [Click here](https://docs.codecov.io/docs/carryforward-flags?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=crypto-org-chain#carryforward-flags-in-the-pull-request-comment) to find out more.

| [Impacted Files](https://codecov.io/gh/crypto-org-chain/chain-main/pull/857?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=crypto-org-chain) | Coverage Δ | |
|---|---|---|
| [x/icaauth/types/types.go](https://codecov.io/gh/crypto-org-chain/chain-main/pull/857/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=crypto-org-chain#diff-eC9pY2FhdXRoL3R5cGVzL3R5cGVzLmdv) | `0.00% <0.00%> (-100.00%)` | :arrow_down: |
| [x/nft/keeper/owners.go](https://codecov.io/gh/crypto-org-chain/chain-main/pull/857/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=crypto-org-chain#diff-eC9uZnQva2VlcGVyL293bmVycy5nbw==) | `17.02% <0.00%> (-68.09%)` | :arrow_down: |
| [x/nft/keeper/collection.go](https://codecov.io/gh/crypto-org-chain/chain-main/pull/857/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=crypto-org-chain#diff-eC9uZnQva2VlcGVyL2NvbGxlY3Rpb24uZ28=) | `23.18% <0.00%> (-49.28%)` | :arrow_down: |
| [x/nft/client/cli/query.go](https://codecov.io/gh/crypto-org-chain/chain-main/pull/857/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=crypto-org-chain#diff-eC9uZnQvY2xpZW50L2NsaS9xdWVyeS5nbw==) | `27.71% <0.00%> (-39.14%)` | :arrow_down: |
| [x/nft/keeper/grpc\_query.go](https://codecov.io/gh/crypto-org-chain/chain-main/pull/857/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=crypto-org-chain#diff-eC9uZnQva2VlcGVyL2dycGNfcXVlcnkuZ28=) | `5.88% <0.00%> (-37.82%)` | :arrow_down: |
| [x/nft/keeper/denom.go](https://codecov.io/gh/crypto-org-chain/chain-main/pull/857/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=crypto-org-chain#diff-eC9uZnQva2VlcGVyL2Rlbm9tLmdv) | `51.28% <0.00%> (-33.34%)` | :arrow_down: |
| [x/nft/client/cli/tx.go](https://codecov.io/gh/crypto-org-chain/chain-main/pull/857/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=crypto-org-chain#diff-eC9uZnQvY2xpZW50L2NsaS90eC5nbw==) | `43.02% <0.00%> (-30.42%)` | :arrow_down: |
| [x/nft/types/msgs.go](https://codecov.io/gh/crypto-org-chain/chain-main/pull/857/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=crypto-org-chain#diff-eC9uZnQvdHlwZXMvbXNncy5nbw==) | `50.00% <0.00%> (-25.00%)` | :arrow_down: |
| [x/icaauth/types/message\_register\_account.go](https://codecov.io/gh/crypto-org-chain/chain-main/pull/857/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=crypto-org-chain#diff-eC9pY2FhdXRoL3R5cGVzL21lc3NhZ2VfcmVnaXN0ZXJfYWNjb3VudC5nbw==) | `0.00% <0.00%> (-25.00%)` | :arrow_down: |
| [x/nft/keeper/keeper.go](https://codecov.io/gh/crypto-org-chain/chain-main/pull/857/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=crypto-org-chain#diff-eC9uZnQva2VlcGVyL2tlZXBlci5nbw==) | `59.42% <0.00%> (-20.29%)` | :arrow_down: |
| ... and [8 more](https://codecov.io/gh/crypto-org-chain/chain-main/pull/857/diff?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=crypto-org-chain) | |

Help us with your feedback. Take ten seconds to tell us [how you rate us](https://about.codecov.io/nps?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=crypto-org-chain). Have a feature suggestion? [Share it here.](https://app.codecov.io/gh/feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=crypto-org-chain)

_Originally posted by @codecov[bot] in https://github.com/crypto-org-chain/chain-main/issues/857#issuecomment-1238850347_

**Comment by tomtau** [comment]
https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md#feature-requests-and-bug-reports
