### ISSUE TITLE
Problem: Lack error check in ExportAppStateAndValidators function

### ISSUE THREAD

**Issue by ThanhNhann** [crypto-org-chain/chain-main#920]
# Background:
- Right now, we don't have the check for the error case in this line 
https://github.com/crypto-org-chain/chain-main/blob/9ca54f5efc02ef1719e403c6050139b1f704f455/app/export.go#L42-L49
so we should add it

# Suggested Design: 
- Update error check for this case

# Acceptance Criteria:
- All test case pass
- Error check was added

**Comment by tomtau** [comment]
@ThanhNhann any detail why the lack of check is an issue? the error is returned and should be checked by the caller?

**Comment by ThanhNhann** [comment]
I think the error should be updated from cosmos-sdk, like @yihuang comment in this: https://github.com/crypto-org-chain/chain-main/pull/918#discussion_r1097128295, and after that, we can merge my pr
